/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-07-03 08:31:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ActualizarProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Registrar Producto</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#c5dec9\">\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\">Actualizar Productos</h1>\r\n");
      out.write("<form action=\"ControladorProducto\" method=\"post\">\r\n");
 
	String codigo=request.getAttribute("codigo").toString();
	String descrip=(request.getAttribute("descripcion")!=null)?request.getAttribute("descripcion").toString():"";
	String esta=(request.getAttribute("estado")!=null)?request.getAttribute("estado").toString():"";
	String nom=(request.getAttribute("nombre")!=null)?request.getAttribute("nombre").toString():"";
	String preCom=(request.getAttribute("precioCom")!=null)?request.getAttribute("precioCom").toString():"";
	String preVe=(request.getAttribute("precioVen")!=null)?request.getAttribute("precioVen").toString():"";

      out.write("\r\n");
      out.write("<table border=\"2\" align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Codigo</td>\r\n");
      out.write("<td><input type=\"text\" name=\"codigo\" value=\"");
      out.print(codigo);
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<td>Nombre</td>\r\n");
      out.write("<td><input type=\"text\" name=\"nombre\" value=\"");
      out.print(nom);
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Precio</td>\r\n");
      out.write("<td><input type=\"text\" name=\"precioCom\" value=\"");
      out.print(preCom);
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>PrecioVen</td>\r\n");
      out.write("<td><input type=\"text\" name=\"precioVen\" value=\"");
      out.print(preVe);
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Estado</td>\r\n");
      out.write("<td><input type=\"text\" name=\"estado\" value=\"");
      out.print(esta);
      out.write("\" ></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Descrip</td>\r\n");
      out.write("<td><input type=\"text\" name=\"descripcion\" value=\"");
      out.print(descrip);
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td colspan=\"2\"  align=\"center\" >\r\n");
      out.write("<input type=\"submit\" value=\"Actualizar Producto\">\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
